### ISSUE TITLE
Cors

### ISSUE THREAD

**Issue by neilsch75** [jchristn/RestDb#1]
Hi 

First of All i want to thank you for this amazing simple Api first C# Api i see so simple :))

I want to know if its possible to CORS with this RestDb ?

If so how ? 

I dont mind editing adding code if must ... but maybe you have allready implemented such logic ...

I had a look at the docs and the Readme dont see any cors ... maybe Im just stupid!

I would Appreciate yout advise or help so much !

Regards

NS...

**Comment by neilsch75** [comment]
Sorry I was Stupid works perfectly ;)))

**Comment by jchristn** [comment]
Hi @neilsch75 I'm glad it works for you!  Please let me know if any other issues!  Cheers

**Comment by neilsch75** [comment]
Hey man

I wanted to know why not make a proper coati g for restDb give it that same
name even with nice design web ui etc and provide it as a service but give
full functionality to 1 db and all rest services if you know what i mean
...you know how hard it was to find a restdb where i jave full
functionality free for atleast 1 database ... after that you can charge a
subscription something like cdata ... think about it ... and thanx again
mate it awesome ..

Regards

N

**Comment by jchristn** [comment]
Hi @neilsch75 sorry I just saw this comment!  Thanks so much for your feedback!  I've been thinking of extending it to allow API consumers to create and manage databases and tables, which would allow it to become a hosted service.  I'll give it some consideration.  Thanks for the positive feedback!

**Comment by neilsch75** [comment]
Anytime i would love to help if ever needed have xp in multiple languages
and dont mind investing in this as other services are so complicated and
expensive this is very simple api solution... and working great in my
hybrid app especially the sql intergration ...take care ...

Regards

Neil Schutte
